--[[ egg groups
monster   -reptilian but not draconic
frog
fish
aquatic   -describes invertebrates like squids
insect
bird
field     -most pokemon go here if they don't belong elsewhere
fairy
plant
humanoid
inorganic -rocks, metals, machines
amorphous -blob-like or otherwise abnormal
dragon
undead
cant      -pokemon that can't breed go here
]]

poke = {
  --[[
    name = name of the pokemon, easy
    sprite = used if the sprite name is different from the name
    anim = boolean that states whether the sprite animates or not. reserved for baba
    types = table of the types the pokemon has. list of types above
    gendm,gendf = odds of the pokemon being a certain gender. 0.2,0.3 means that there's 20% chance of male, 30% chance of female, and 50% chance of other.
    gaypb = odds of the pokemon being gay. preference only affects breeding, and yes, gay breeding can happen
    catch = the odds that a pokemon will be caught. an integer between 0 and 255, with 255 being very high likelihood (not guaranteed?) of catching and 0 being impossible
    expy = the amount of exp you'll get from defeating the pokemon. number between 1 and 255. https://textuploader.com/atre4
    able = lists the first, second and hidden abilities that the pokemon can have. if the pokemon can only have 1 ability, then both first and second need to be that ability
    egg = numbers corresponding to the egg groups that the pokemon is in. numbers are found above in egg_group
    growth = how quickly the pokemon goes between levels. options are "fast", "medium_fast", "medium_slow", "slow", "erratic", and "fluctuating" https://bulbapedia.bulbagarden.net/wiki/Experience#Relation_to_level
    attacks = list of attacks the pokemon can learn, by level. example:
    {
      "tm" = {
        "swim",
      },
      "evolve" = {
        "explosion 2",
      },
      1 = {
        "tackle",
        "explosion",
      },
      3 = {
        "hyper beam",
      },
    },
  ]]
  {
    name = "bab",
    types = {"you"},
    gendm = 0.1,
    gendf = 0.88,
    gaypb = 0.7,
    catch = 45,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"field"},
    growth = "medium_slow",
    attacks = {},
  },
  {
    name = "babi",
    types = {"you","psychic"},
    gendm = 0.1,
    gendf = 0.88,
    gaypb = 0.7,
    catch = 45,
    expy = 141,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"field"},
    growth = "medium_slow",
  },
  {
    name = "babber",
    types = {"you","psychic"},
    gendm = 0.1,
    gendf = 0.88,
    gaypb = 0.7,
    catch = 45,
    expy = 208,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"field"},
    growth = "medium_slow",
  },
  {
    name = "keek",
    types = {"push"},
    gendm = 0.8,
    gendf = 0.2,
    gaypb = 0.5,
    catch = 45,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"inorganic"},
    growth = "medium_slow",
  },
  {
    name = "meem",
    types = {"defeat"},
    gendm = 0.05,
    gendf = 0.005,
    gaypb = 0,
    catch = 45,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"humanoid"},
    growth = "medium_slow",
  },
  {
    name = "kat",
    types = {"you"},
    gendm = 0.05,
    gendf = 0.95,
    gaypb = 0.3,
    catch = 90,
    expy = 72,
    able = {},
    egg = {"field"},
    growth = "medium_slow",
    attacks = {},
  },
  {
    name = "copkat",
    types = {"you","fighting"},
    gendm = 0.05,
    gendf = 0.95,
    gaypb = 0.3,
    catch = 90,
    expy = 72,
    able = {},
    egg = {"field"},
    growth = "medium_slow",
    attacks = {},
  },
  {
    name = "flof",
    types = {"you"},
    gendm = 0.88,
    gendf = 0.1,
    gaypb = 0.7,
    catch = 90,
    expy = 72,
    able = {
      first = "fluffy",
      second = "fur_coat",
      hidden = "unaware",
    },
    egg = {"field"},
    growth = "medium_slow",
    attacks = {},
  },
  {
    name = "furlof",
    types = {"you","water"},
    gendm = 0.88,
    gendf = 0.1,
    gaypb = 0.7,
    catch = 45,
    expy = 90,
    able = {
      first = "fluffy",
      second = "fur_coat",
      hidden = "unaware",
    },
    egg = {"field"},
    growth = "medium_slow",
    attacks = {},
  },
  {
    name = "skul",
    types = {"defeat"},
    gendm = 0.6,
    gendf = 0.3,
    gaypb = 0.6,
    catch = 240,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"undead"},
    growth = "medium_slow",
  },
  {
    name = "skulnbon",
    types = {"defeat"},
    gendm = 0.6,
    gendf = 0.3,
    gaypb = 0.6,
    catch = 120,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"undead"},
    growth = "medium_slow",
  },
  {
    name = "kirb",
    types = {"normal"},
    gendm = 0.9,
    gendf = 0,
    gaypb = 0,
    catch = 200,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"amorphous","humanoid"},
    growth = "fast",
  },
  {
    name = "ghost fren",
    sprite = "ghostfren",
    types = {"ghost"},
    gendm = 0.4,
    gendf = 0.4,
    gaypb = 0,
    catch = 190,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"amorphous","undead"},
    growth = "medium_fast",
  },
  {
    name = "wog",
    types = {"normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0.001,
    catch = 220,
    expy = 55,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"bird"},
    growth = "medium_slow",
  },
  {
    name = "wogotch",
    types = {"normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0.001,
    catch = 150,
    expy = 113,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"bird"},
    growth = "medium_slow",
  },
  {
    name = "snoboy",
    types = {"ice","normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 230,
    expy = 70,
    able = {
      first = "hydration",
      second = "ice_body",
      hidden = "snow_warning",
    },
    egg = {"inorganic"},
    growth = "medium_fast",
  },
  {
    name = "snoman",
    types = {"ice","normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 115,
    expy = 115,
    able = {
      first = "hydration",
      second = "ice_body",
      hidden = "snow_warning",
    },
    egg = {"inorganic"},
    growth = "medium_fast",
  },
  {
    name = "wurm",
    types = {"bug"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 250,
    expy = 50,
    able = {
      first = "frisk",
      second = "harvest",
      hidden = "unnerve",
    },
    egg = {"insect"},
    growth = "fast",
  },
  {
    name = "sneel",
    types = {"water"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 240,
    expy = 65,
    able = {
      first = "slow_start",
      second = "storm_drain",
      hidden = "solid_rock",
    },
    egg = {"aquatic"},
    growth = "medium_fast",
  },
  {
    name = "sneelectric",
    types = {"water","electric"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 120,
    expy = 100,
    able = {
      first = "swift_swim",
      second = "storm_drain",
      hidden = "solid_rock",
    },
    egg = {"aquatic"},
    growth = "medium_fast",
  },
   {
    name = "fishe",
    types = {"water","normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 240,
    expy = 65,
    able = {
      first = "run_away",
      second = "torrent",
      hidden = "water_bubble",
    },
    egg = {"aquatic"},
    growth = "medium_fast",
  },
   {
    name = "starrfishe",
    types = {"water"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 200,
    expy = 72,
    able = {
      first = "sticky_hold",
      second = "oblivious",
      hidden = "gooey",
    },
    egg = {"aquatic"},
    growth = "medium_fast",
  },
   {
    name = "migri",
    types = {"you","defeat"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 80,
    expy = 100,
    able = {
      first = "levitate",
      second = "infiltrator",
      hidden = "magic_guard",
    },
    egg = {"amorphous"},
    growth = "medium_slow",
  },
  {
    name = "oddish",
    types = {"grass","poison"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 255,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"plant"},
    growth = "medium_slow",
  },
  {
    name = "magnemite",
    types = {"steel","electric"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 190,
    expy = 65,
    able = {
      first = "magnet_pull",
      second = "sturdy",
      hidden = "analytic",
    },
    egg = {"cant"},
    growth = "medium_fast",
  },
  {
    name = "beldum",
    types = {"steel","psychic"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 3,
    expy = 60,
    able = {
      first = "clear_body",
      second = "clear_body",
      hidden = "light_metal",
    },
    egg = {"cant"},
    growth = "slow",
  },
  {
    name = "sentret",
    types = {"normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 255,
    expy = 43,
    able = {
      first = "run_away",
      second = "keen_eye",
      hidden = "frisk",
    },
    egg = {"field"},
    growth = "medium_fast",
  },
  {
    name = "eevee",
    types = {"normal"},
    gendm = 0.875,
    gendf = 0.125,
    gaypb = 0,
    catch = 45,
    expy = 65,
    able = {
      first = "run_away",
      second = "adaptability",
      hidden = "anticipation",
    },
    egg = {"field"},
    growth = "medium_fast",
  },
  {
    name = "koffing",
    types = {"poison"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 190,
    expy = 68,
    able = {
      first = "levitate",
      second = "nil",
      hidden = "nil",
    },
    egg = {"amorphous"},
    growth = "medium_fast",
  },
  {
    name = "shuppet",
    types = {"ghost"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 225,
    expy = 59,
    able = {
      first = "insomnia",
      second = "frisk",
      hidden = "cursed_body",
    },
    egg = {"amorphous"},
    growth = "medium_fast",
  },
  {
    name = "litwick",
    types = {"ghost","fire"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 190,
    expy = 55,
    able = {
      first = "flash_fire",
      second = "flame_body",
      hidden = "infiltrator",
    },
    egg = {"amorphous"},
    growth = "medium_slow",
  },
  {
    name = "lampent",
    types = {"ghost","fire"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 90,
    expy = 130,
    able = {
      first = "flash_fire",
      second = "flame_body",
      hidden = "infiltrator",
    },
    egg = {"amorphous"},
    growth = "medium_slow",
  },
  {
    name = "solosis",
    types = {"psychic"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 200,
    expy = 58,
    able = {
      first = "overcoat",
      second = "magic_guard",
      hidden = "regenerator",
    },
    egg = {"amorphous"},
    growth = "medium_slow",
  },
  {
    name = "duosion",
    types = {"psychic"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 100,
    expy = 130,
    able = {
      first = "overcoat",
      second = "magic_guard",
      hidden = "regenerator",
    },
    egg = {"amorphous"},
    growth = "medium_slow",
  },
  {
    name = "dratini",
    types = {"dragon"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 45,
    expy = 60,
    able = {
      first = "shed_skin",
      second = "shed_skin",
      hidden = "marvel_scale",
    },
    egg = {"aquatic","dragon"},
    growth = "slow",
  },
  {
    name = "azurill",
    types = {"normal","fairy"},
    gendm = 0.25,
    gendf = 0.75,
    gaypb = 0,
    catch = 150,
    expy = 38,
    able = {
      first = "thick_fat",
      second = "huge_power",
      hidden = "sap_sipper",
    },
    egg = {"cant"},
    growth = "fast",
  },
  {
    name = "drifloon",
    types = {"ghost","flying"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 125,
    expy = 70,
    able = {
      first = "aftermath",
      second = "unburden",
      hidden = "flare_boost",
    },
    egg = {"amorphous"},
    growth = "fluctuating",
  },
  {
    name = "spiritomb",
    types = {"ghost","dark"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 100,
    expy = 170,
    able = {
      first = "pressure",
      second = "pressure",
      hidden = "infiltrator",
    },
    egg = {"amorphous"},
    growth = "medium_fast",
  },
  {
    name = "pyukumuku",
    types = {"water"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 60,
    expy = 144,
    able = {
      first = "innards_out",
      second = "innards_out",
      hidden = "unaware",
    },
    egg = {"aquatic"},
    growth = "fast",
  },
  {
    name = "baba",
    anim = true,
    types = {"you"},
    gendm = 0,
    gendf = 1,
    gaypb = 1,
    catch = 40,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"cant"},
    growth = "slow",
  },
  {
    name = "missingno.",
    sprite = "missingno",
    types = {},
    gendm = 0,
    gendf = 0,
    gaypb = 0,
    catch = 255,
    expy = 0,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"cant"},
    growth = "erratic",
  },
  {
    name = "indexnil",
    types = {},
    gendm = 0,
    gendf = 0,
    gaypb = 0,
    catch = 255,
    expy = 0,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"cant"},
    growth = "erratic",
  },
}

poke_i = {}
for i,v in ipairs(poke) do
  poke[v.name] = v
  poke_i[v.name] = i
end