types = {
  you = {
    you = 1,
    defeat = 1,
    push = 2,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 1,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 1,
  },
  defeat = {
    you = 2,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 1,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 1,
  },
  push = {
    you = 1,
    defeat = 2,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 2,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 1,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 1,
  },
  grass = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 0.5,
    fire = 0.5,
    water = 2,
    electric = 1,
    ice = 1,
    ground = 2,
    rock = 2,
    flying = 0.5,
    poison = 0.5,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 0.5,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 0.5,
    dragon = 0.5,
  },
  fire = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 2,
    fire = 0.5,
    water = 0.5,
    electric = 1,
    ice = 2,
    ground = 1,
    rock = 0.5,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 2,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 2,
    dragon = 0.5,
  },
  water = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 0.5,
    fire = 2,
    water = 0.5,
    electric = 1,
    ice = 1,
    ground = 2,
    rock = 2,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 1,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 0.5,
  },
  electric = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 0.5,
    fire = 1,
    water = 2,
    electric = 0.5,
    ice = 1,
    ground = 0,
    rock = 1,
    flying = 2,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 2,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 0.5,
  },
  ice = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 2,
    fire = 2,
    water = 2,
    electric = 1,
    ice = 2,
    ground = 2,
    rock = 1,
    flying = 2,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 2,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 2,
  },
  ground = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 0.5,
    fire = 2,
    water = 1,
    electric = 2,
    ice = 1,
    ground = 1,
    rock = 2,
    flying = 0,
    poison = 2,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 2,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 0.5,
    dragon = 1,
  },
  rock = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 2,
    water = 1,
    electric = 1,
    ice = 2,
    ground = 0.5,
    rock = 1,
    flying = 2,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 0.5,
    fairy = 1,
    fighting = 0.5,
    psychic = 1,
    bug = 2,
    dragon = 1,
  },
  flying = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 2,
    fire = 1,
    water = 1,
    electric = 0.5,
    ice = 1,
    ground = 1,
    rock = 0.5,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 0.5,
    fairy = 1,
    fighting = 2,
    psychic = 1,
    bug = 2,
    dragon = 1,
  },
  poison = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 2,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 0.5,
    rock = 0.5,
    flying = 1,
    poison = 0.5,
    normal = 1,
    ghost = 0.5,
    dark = 1,
    steel = 0,
    fairy = 2,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 1,
  },
  normal = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 0.5,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 0,
    dark = 1,
    steel = 0.5,
    fairy = 1,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 1,
  },
  ghost = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 1,
    normal = 0,
    ghost = 2,
    dark = 0.5,
    steel = 1,
    fairy = 1,
    fighting = 1,
    psychic = 2,
    bug = 1,
    dragon = 1,
  },
  dark = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 2,
    dark = 0.5,
    steel = 1,
    fairy = 0.5,
    fighting = 0.5,
    psychic = 2,
    bug = 1,
    dragon = 1,
  },
  steel = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 0.5,
    water = 0.5,
    electric = 0.5,
    ice = 2,
    ground = 1,
    rock = 2,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 0.5,
    fairy = 2,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 1,
  },
  fairy = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 0.5,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 0.5,
    normal = 1,
    ghost = 1,
    dark = 2,
    steel = 0.5,
    fairy = 1,
    fighting = 2,
    psychic = 1,
    bug = 1,
    dragon = 2,
  },
  fighting = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 2,
    ground = 1,
    rock = 2,
    flying = 0.5,
    poison = 0.5,
    normal = 2,
    ghost = 0,
    dark = 2,
    steel = 1,
    fairy = 0.5,
    fighting = 1,
    psychic = 0.5,
    bug = 0.5,
    dragon = 1,
  },
  psychic = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 2,
    normal = 1,
    ghost = 1,
    dark = 0,
    steel = 0.5,
    fairy = 1,
    fighting = 2,
    psychic = 0.5,
    bug = 1,
    dragon = 1,
  },
  bug = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 2,
    fire = 0.5,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 0.5,
    poison = 0.5,
    normal = 1,
    ghost = 0.5,
    dark = 2,
    steel = 0.5,
    fairy = 0.5,
    fighting = 0.5,
    psychic = 2,
    bug = 1,
    dragon = 1,
  },
  dragon = {
    you = 1,
    defeat = 1,
    push = 1,
    grass = 1,
    fire = 1,
    water = 1,
    electric = 1,
    ice = 1,
    ground = 1,
    rock = 1,
    flying = 1,
    poison = 1,
    normal = 1,
    ghost = 1,
    dark = 1,
    steel = 0.5,
    fairy = 0,
    fighting = 1,
    psychic = 1,
    bug = 1,
    dragon = 2,
  },
}

--[[ egg groups
monster   -reptilian but not draconic
frog
fish
aquatic   -describes invertebrates like squids
insect
bird
field     -most pokemon go here if they don't belong elsewhere
fairy
plant
humanoid
inorganic -rocks, metals, machines
amorphous -blob-like or otherwise abnormal
dragon
undead
cant      -pokemon that can't breed go here
]]

poke = {
  --[[
    name = name of the pokemon, easy
    sprite = used if the sprite name is different from the name
    anim = boolean that states whether the sprite animates or not. reserved for baba
    types = table of the types the pokemon has. list of types above
    gendm,gendf = odds of the pokemon being a certain gender. 0.2,0.3 means that there's 20% chance of male, 30% chance of female, and 50% chance of other.
    gaypb = odds of the pokemon being gay. preference only affects breeding, and yes, gay breeding can happen
    catch = the odds that a pokemon will be caught. an integer between 0 and 255, with 255 being very high likelihood (not guaranteed?) of catching and 0 being impossible
    expy = the amount of exp you'll get from defeating the pokemon. number between 1 and 255
    able = lists the first, second and hidden abilities that the pokemon can have. if the pokemon can only have 1 ability, then both first and second need to be that ability
    egg = numbers corresponding to the egg groups that the pokemon is in. numbers are found above in egg_group
    growth = how quickly the pokemon goes between levels. options are "fast", "medium_fast", "medium_slow", "slow", "erratic", and "fluctuating" https://bulbapedia.bulbagarden.net/wiki/Experience#Relation_to_level
  ]]
  {
    name = "bab",
    types = {"you"},
    gendm = 0.1,
    gendf = 0.85,
    gaypb = 0.7,
    catch = 45,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"field"},
    growth = "medium_slow",
  },
  {
    name = "keek",
    types = {"push"},
    gendm = 0.8,
    gendf = 0.2,
    gaypb = 0.5,
    catch = 45,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"inorganic"},
    growth = "medium_slow",
  },
  {
    name = "meem",
    types = {"defeat"},
    gendm = 0.05,
    gendf = 0.005,
    gaypb = 0,
    catch = 45,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"humanoid"},
    growth = "medium_slow",
  },
  {
    name = "skul",
    types = {"defeat"},
    gendm = 0.6,
    gendf = 0.3,
    gaypb = 0.6,
    catch = 240,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"undead"},
    growth = "medium_slow",
  },
  {
    name = "skulnbon",
    types = {"defeat"},
    gendm = 0.6,
    gendf = 0.3,
    gaypb = 0.6,
    catch = 120,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"undead"},
    growth = "medium_slow",
  },
  {
    name = "kirb",
    types = {"normal"},
    gendm = 0.9,
    gendf = 0,
    gaypb = 0,
    catch = 200,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"amorphous","humanoid"},
    growth = "fast",
  },
  {
    name = "ghost fren",
    sprite = "ghostfren",
    types = {"ghost"},
    gendm = 0.4,
    gendf = 0.4,
    gaypb = 0,
    catch = 190,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"amorphous","undead"},
    growth = "medium_fast",
  },
  {
    name = "wog",
    types = {"normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0.001,
    catch = 220,
    expy = 55,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"bird"},
    growth = "medium_slow",
  },
  {
    name = "wogotch",
    types = {"normal"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0.001,
    catch = 150,
    expy = 113,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"bird"},
    growth = "medium_slow",
  },
  {
    name = "oddish",
    types = {"grass","poison"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 255,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"plant"},
    growth = "medium_slow",
  },
  {
    name = "magnemite",
    types = {"steel","electric"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 190,
    expy = 65,
    able = {
      first = "magnet_pull",
      second = "sturdy",
      hidden = "analytic",
    },
    egg = {"cant"},
    growth = "medium_fast",
  },
  {
    name = "beldum",
    types = {"steel","psychic"},
    gendm = 0.5,
    gendf = 0.5,
    gaypb = 0,
    catch = 3,
    expy = 60,
    able = {
      first = "clear_body",
      second = "clear_body",
      hidden = "light_metal",
    },
    egg = {"cant"},
    growth = "slow",
  },
  {
    name = "baba",
    anim = true,
    types = {"you"},
    gendm = 0,
    gendf = 1,
    gaypb = 1,
    catch = 40,
    expy = 64,
    able = {
      first = nil,
      second = nil,
      hidden = nil,
    },
    egg = {"cant"},
    growth = "slow",
  },
}

pokedex_i = {}
for i,v in ipairs(poke) do
  pokedex_i[v.name] = i
end